A=input('Enter the first number\n')
B=input('Enter the second number\n')
A=float(A)
B=float(B)
C= (A+B)
D=(A-B)
E =(A*B)
F= (A/B)
print('addition:', C)
print('subtraction:', D)
print('multiplication:', E)
print('Division:', F)